# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimetableUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.CharField(max_length=20)),
                ('grade', models.DecimalField(decimal_places=0, default=1, max_digits=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='course_of_user',
            name='idList',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Course_of_user',
        ),
    ]
