# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_auto_20161124_1858'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(default='', max_length=100)),
                ('code', models.CharField(default='', max_length=100)),
                ('for_class', models.CharField(default='', max_length=100)),
                ('credits', models.CharField(default='', max_length=100)),
                ('title', models.CharField(default='', max_length=100)),
                ('department', models.CharField(default='', max_length=100)),
                ('professor', models.CharField(default='', max_length=100)),
                ('time', models.CharField(default='', max_length=100)),
                ('location', models.CharField(default='', max_length=100)),
                ('obligatory', models.CharField(default='', max_length=100)),
                ('language', models.CharField(default='', max_length=100)),
                ('duration', models.CharField(default='', max_length=100)),
                ('prerequisite', models.CharField(default='', max_length=100)),
                ('note', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SelectedCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='', max_length=20)),
                ('code', models.CharField(default='', max_length=20)),
                ('semester', models.CharField(default='', max_length=6)),
            ],
        ),
        migrations.DeleteModel(
            name='TimetableUser',
        ),
    ]
