# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 22:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseID', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=15)),
                ('book', models.CharField(max_length=50)),
                ('create', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Course_of_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('user_dept', models.CharField(max_length=20)),
                ('user_grade', models.DecimalField(decimal_places=0, default=1, max_digits=1)),
                ('time_table', models.CharField(max_length=5000)),
                ('returnarr', models.CharField(max_length=100)),
                ('hadSaved', models.BooleanField(default=False)),
                ('create', models.DateTimeField()),
                ('idList', models.ManyToManyField(to='timetable.Course')),
            ],
        ),
    ]
